### ISSUE TITLE
printTexts TextStyle not working

### ISSUE THREAD

**Issue by Chanthuon168** [shangmisunmi/SunmiPrinterXSample#2]
setTextSize not working

**Comment by Limoer96** [comment]
> setTextSize not working

printTexts `styles` only support `setAlign` now.

**Comment by Uma1r** [comment]
Hi, any timeline on when styles will be supported in `printTexts`?

**Comment by tvqphong001** [comment]
Me too, need support

**Comment by git175010415** [comment]
please update printer service in system to v6.5.0+.

**Comment by git175010415** [comment]
PrinerService in 6.5.0+ will solve it.
